import type { Metadata } from 'next';

import { ThemeSwitcher } from '@/app/components/ThemeSwitcher';
import { inter } from '@/app/fonts';
import { ThemeStoreProvider } from '@/app/store/ThemeStoreContext';
import setColorThemeScript from '@/app/theme/setColorThemeScript';

import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        {/* Blocking script to set color mode preference before content is shown */}
        <script dangerouslySetInnerHTML={{ __html: setColorThemeScript }} />

        <ThemeStoreProvider>
          {children}
          <ThemeSwitcher className="absolute top-2 right-2" />
        </ThemeStoreProvider>
      </body>
    </html>
  );
}
